<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/wallet.proto

namespace GPBMetadata\Protos;

class Wallet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
›
protos/wallet.protowallet"(
GenerateWalletRequest
network (	"h
GenerateWalletResponse
public_address (	
private_key (	
network (	
mnemonic (	2`
WalletServiceO
GenerateWallet.wallet.GenerateWalletRequest.wallet.GenerateWalletResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

